2023-09-08 15:57:51 base.py[line:181] INFO Scheduler started
2023-09-08 15:58:29 base.py[line:181] INFO Scheduler started
2023-09-08 15:58:35 log.py[line:241] WARNING Not Found: /
2023-09-08 15:58:35 log.py[line:241] WARNING Not Found: /
2023-09-08 15:58:35 log.py[line:241] WARNING Not Found: /favicon.ico
2023-09-08 15:58:37 log.py[line:241] ERROR Internal Server Error: /admin/
Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\GitHub\linerunner-backend\.venv\lib\site-packages\django\contrib\sessions\backends\base.py", line 187, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\GitHub\linerunner-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Administrator\Documents\GitHub\linerunner-backend\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Administrator\Documents\GitHub\linerunner-backend\.venv\lib\site-packages\pymysql\cursors.py", line 153, in execute
    result = self._query(query)
  File "C:\Users\Administrator\Documents\GitHub\linerunner-backend\.venv\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "C:\Users\Administrator\Documents\GitHub\linerunner-backend\.venv\lib\site-packages\pymysql\connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\Administrator\Documents\GitHub\linerunner-backend\.venv\lib\site-packages\pymysql\connections.py", line 822, in _read_query_result
    result.read()
  File "C:\Users\Administrator\Documents\GitHub\linerunner-backend\.venv\lib\site-packages\pymysql\connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\Administrator\Documents\GitHub\linerunner-backend\.venv\lib\site-packages\pymysql\connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "C:\Users\Administrator\Documents\GitHub\linerunner-backend\.venv\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\Administrator\Documents\GitHub\linerunner-backend\.venv\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.ProgrammingError: (1146, "Table 'django_api.django_session' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\Documents\GitHub\linerunner-backend\.venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Administrator\Documents\GitHub\linerunner-backend\.venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Administrator\Documents\GitHub\linerunner-backend\.venv\lib\site-packages\django\contrib\admin\sites.py", line 261, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "C:\Users\Administrator\Documents\GitHub\linerunner-backend\.venv\lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Administrator\Documents\GitHub\linerunner-backend\.venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "C:\Users\Administrator\Documents\GitHub\linerunner-backend\.venv\lib\site-packages\django\contrib\admin\sites.py", line 230, in inner
    if not self.has_permission(request):
  File "C:\Users\Administrator\Documents\GitHub\linerunner-backend\.venv\lib\site-packages\django\contrib\admin\sites.py", line 203, in has_permission
    return request.user.is_active and request.user.is_staff
  File "C:\Users\Administrator\Documents\GitHub\linerunner-backend\.venv\lib\site-packages\django\utils\functional.py", line 266, in inner
    self._setup()
  File "C:\Users\Administrator\Documents\GitHub\linerunner-backend\.venv\lib\site-packages\django\utils\functional.py", line 419, in _setup
    self._wrapped = self._setupfunc()
  File "C:\Users\Administrator\Documents\GitHub\linerunner-backend\.venv\lib\site-packages\django\contrib\auth\middleware.py", line 25, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "C:\Users\Administrator\Documents\GitHub\linerunner-backend\.venv\lib\site-packages\django\contrib\auth\middleware.py", line 11, in get_user
    request._cached_user = auth.get_user(request)
  File "C:\Users\Administrator\Documents\GitHub\linerunner-backend\.venv\lib\site-packages\django\contrib\auth\__init__.py", line 191, in get_user
    user_id = _get_user_session_key(request)
  File "C:\Users\Administrator\Documents\GitHub\linerunner-backend\.venv\lib\site-packages\django\contrib\auth\__init__.py", line 60, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "C:\Users\Administrator\Documents\GitHub\linerunner-backend\.venv\lib\site-packages\django\contrib\sessions\backends\base.py", line 53, in __getitem__
    return self._session[key]
  File "C:\Users\Administrator\Documents\GitHub\linerunner-backend\.venv\lib\site-packages\django\contrib\sessions\backends\base.py", line 192, in _get_session
    self._session_cache = self.load()
  File "C:\Users\Administrator\Documents\GitHub\linerunner-backend\.venv\lib\site-packages\django\contrib\sessions\backends\db.py", line 42, in load
    s = self._get_session_from_db()
  File "C:\Users\Administrator\Documents\GitHub\linerunner-backend\.venv\lib\site-packages\django\contrib\sessions\backends\db.py", line 32, in _get_session_from_db
    return self.model.objects.get(
  File "C:\Users\Administrator\Documents\GitHub\linerunner-backend\.venv\lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\Administrator\Documents\GitHub\linerunner-backend\.venv\lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
  File "C:\Users\Administrator\Documents\GitHub\linerunner-backend\.venv\lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\Administrator\Documents\GitHub\linerunner-backend\.venv\lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Users\Administrator\Documents\GitHub\linerunner-backend\.venv\lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "C:\Users\Administrator\Documents\GitHub\linerunner-backend\.venv\lib\site-packages\django\db\models\sql\compiler.py", line 1560, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Administrator\Documents\GitHub\linerunner-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
  File "C:\Users\Administrator\Documents\GitHub\linerunner-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "C:\Users\Administrator\Documents\GitHub\linerunner-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\Administrator\Documents\GitHub\linerunner-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Administrator\Documents\GitHub\linerunner-backend\.venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Administrator\Documents\GitHub\linerunner-backend\.venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\Administrator\Documents\GitHub\linerunner-backend\.venv\lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\Administrator\Documents\GitHub\linerunner-backend\.venv\lib\site-packages\pymysql\cursors.py", line 153, in execute
    result = self._query(query)
  File "C:\Users\Administrator\Documents\GitHub\linerunner-backend\.venv\lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "C:\Users\Administrator\Documents\GitHub\linerunner-backend\.venv\lib\site-packages\pymysql\connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "C:\Users\Administrator\Documents\GitHub\linerunner-backend\.venv\lib\site-packages\pymysql\connections.py", line 822, in _read_query_result
    result.read()
  File "C:\Users\Administrator\Documents\GitHub\linerunner-backend\.venv\lib\site-packages\pymysql\connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
  File "C:\Users\Administrator\Documents\GitHub\linerunner-backend\.venv\lib\site-packages\pymysql\connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "C:\Users\Administrator\Documents\GitHub\linerunner-backend\.venv\lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\Administrator\Documents\GitHub\linerunner-backend\.venv\lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
django.db.utils.ProgrammingError: (1146, "Table 'django_api.django_session' doesn't exist")
2023-09-08 15:58:51 base.py[line:181] INFO Scheduler started
2023-09-08 15:59:00 base.py[line:181] INFO Scheduler started
2023-09-08 16:01:43 base.py[line:181] INFO Scheduler started
2023-09-08 16:02:46 base.py[line:181] INFO Scheduler started
2023-09-08 16:06:22 base.py[line:181] INFO Scheduler started
2023-09-08 16:25:19 base.py[line:181] INFO Scheduler started
2023-09-08 16:25:43 base.py[line:181] INFO Scheduler started
2023-09-08 16:27:10 base.py[line:181] INFO Scheduler started
2023-09-08 16:28:39 base.py[line:181] INFO Scheduler started
2023-09-08 16:28:49 base.py[line:181] INFO Scheduler started
2023-09-09 03:41:15 base.py[line:181] INFO Scheduler started
2023-09-09 03:41:23 base.py[line:181] INFO Scheduler started
2023-09-09 03:44:47 base.py[line:181] INFO Scheduler started
2023-09-09 03:44:53 base.py[line:181] INFO Scheduler started
2023-09-22 15:29:14 base.py[line:181] INFO Scheduler started
2023-09-22 15:29:57 base.py[line:181] INFO Scheduler started
2023-09-22 15:30:02 base.py[line:181] INFO Scheduler started
2023-09-22 15:30:11 base.py[line:181] INFO Scheduler started
2023-09-22 15:30:16 base.py[line:181] INFO Scheduler started
2023-09-22 15:37:21 log.py[line:224] WARNING Not Found: /table
2023-09-22 15:37:23 log.py[line:224] WARNING Not Found: /table
2023-09-22 15:37:35 log.py[line:224] WARNING Not Found: /table
2023-09-22 15:37:55 log.py[line:224] WARNING Not Found: /table
2023-09-22 15:37:58 log.py[line:224] WARNING Not Found: /table
2023-09-22 15:37:59 log.py[line:224] WARNING Not Found: /table
2023-09-22 15:37:59 log.py[line:224] WARNING Not Found: /table
2023-09-22 15:39:58 log.py[line:224] WARNING Not Found: /table
2023-09-22 15:40:05 log.py[line:224] WARNING Not Found: /table
2023-09-22 15:41:51 log.py[line:224] WARNING Not Found: /table
2023-09-22 15:47:40 log.py[line:224] WARNING Not Found: /table
2023-11-02 13:03:29 base.py[line:181] INFO Scheduler started
2023-11-02 13:03:41 log.py[line:224] WARNING Not Found: /
2023-11-02 13:03:41 log.py[line:224] WARNING Not Found: /favicon.ico
2023-11-02 13:13:22 base.py[line:181] INFO Scheduler started
2023-11-02 13:15:25 base.py[line:181] INFO Scheduler started
2023-11-02 13:28:23 autoreload.py[line:251] INFO C:\Users\Administrator\Documents\GitHub\linerunner-backend\apps\user\models.py changed, reloading.
2023-11-02 13:28:25 base.py[line:181] INFO Scheduler started
2023-11-02 13:28:34 autoreload.py[line:251] INFO C:\Users\Administrator\Documents\GitHub\linerunner-backend\apps\user\models.py changed, reloading.
2023-11-02 13:28:35 base.py[line:181] INFO Scheduler started
2023-11-02 13:35:05 autoreload.py[line:251] INFO C:\Users\Administrator\Documents\GitHub\linerunner-backend\linerunner\settings.py changed, reloading.
2023-11-02 13:35:07 base.py[line:181] INFO Scheduler started
2023-11-02 13:35:09 autoreload.py[line:251] INFO C:\Users\Administrator\Documents\GitHub\linerunner-backend\apps\user\apps.py changed, reloading.
2023-11-02 13:35:11 base.py[line:181] INFO Scheduler started
2023-11-02 15:19:30 log.py[line:224] WARNING Not Found: /CLodopfuncs.js
2023-11-02 15:28:44 autoreload.py[line:251] INFO C:\Users\Administrator\Documents\GitHub\linerunner-backend\apps\case\models.py changed, reloading.
2023-11-02 15:28:45 base.py[line:181] INFO Scheduler started
2023-11-02 15:29:26 autoreload.py[line:251] INFO C:\Users\Administrator\Documents\GitHub\linerunner-backend\apps\apiTest\models.py changed, reloading.
2023-11-02 15:29:28 base.py[line:181] INFO Scheduler started
2023-11-02 15:29:51 autoreload.py[line:251] INFO C:\Users\Administrator\Documents\GitHub\linerunner-backend\apps\chanDao\models.py changed, reloading.
2023-11-02 15:29:52 base.py[line:181] INFO Scheduler started
2023-11-02 15:30:02 autoreload.py[line:251] INFO C:\Users\Administrator\Documents\GitHub\linerunner-backend\apps\report\models.py changed, reloading.
2023-11-02 15:30:04 base.py[line:181] INFO Scheduler started
2023-11-02 15:30:06 autoreload.py[line:251] INFO C:\Users\Administrator\Documents\GitHub\linerunner-backend\apps\report\models.py changed, reloading.
2023-11-02 15:30:07 base.py[line:181] INFO Scheduler started
2023-11-02 15:30:20 autoreload.py[line:251] INFO C:\Users\Administrator\Documents\GitHub\linerunner-backend\apps\task\models.py changed, reloading.
2023-11-02 15:30:22 base.py[line:181] INFO Scheduler started
2023-11-02 15:30:52 autoreload.py[line:251] INFO C:\Users\Administrator\Documents\GitHub\linerunner-backend\apps\user\models.py changed, reloading.
2023-11-02 15:30:54 base.py[line:181] INFO Scheduler started
2023-11-02 15:31:02 autoreload.py[line:251] INFO C:\Users\Administrator\Documents\GitHub\linerunner-backend\apps\user\models.py changed, reloading.
2023-11-02 15:31:03 base.py[line:181] INFO Scheduler started
2023-11-02 15:31:10 autoreload.py[line:251] INFO C:\Users\Administrator\Documents\GitHub\linerunner-backend\apps\user\models.py changed, reloading.
2023-11-02 15:31:12 base.py[line:181] INFO Scheduler started
2023-11-02 15:31:24 autoreload.py[line:251] INFO C:\Users\Administrator\Documents\GitHub\linerunner-backend\apps\user\models.py changed, reloading.
2023-11-02 15:31:25 base.py[line:181] INFO Scheduler started
2023-11-02 15:31:44 autoreload.py[line:251] INFO C:\Users\Administrator\Documents\GitHub\linerunner-backend\apps\xmfile\models.py changed, reloading.
2023-11-02 15:31:45 base.py[line:181] INFO Scheduler started
2023-11-02 15:32:41 base.py[line:181] INFO Scheduler started
2023-11-02 15:32:55 autoreload.py[line:251] INFO C:\Users\Administrator\Documents\GitHub\linerunner-backend\linerunner\settings.py changed, reloading.
2023-11-02 15:32:57 base.py[line:181] INFO Scheduler started
2023-11-02 15:32:57 base.py[line:181] INFO Scheduler started
2023-11-02 15:33:25 base.py[line:181] INFO Scheduler started
2023-11-02 15:33:34 base.py[line:181] INFO Scheduler started
2023-11-02 15:33:49 base.py[line:181] INFO Scheduler started
2023-11-02 15:34:11 base.py[line:181] INFO Scheduler started
2023-11-02 15:38:26 autoreload.py[line:251] INFO C:\Users\Administrator\Documents\GitHub\linerunner-backend\linerunner\urls.py changed, reloading.
2023-11-02 15:38:27 autoreload.py[line:251] INFO C:\Users\Administrator\Documents\GitHub\linerunner-backend\linerunner\urls.py changed, reloading.
2023-11-02 15:38:27 base.py[line:181] INFO Scheduler started
2023-11-02 15:38:28 base.py[line:181] INFO Scheduler started
2023-11-02 15:38:54 autoreload.py[line:251] INFO C:\Users\Administrator\Documents\GitHub\linerunner-backend\apps\chanDao\admin.py changed, reloading.
2023-11-02 15:38:54 autoreload.py[line:251] INFO C:\Users\Administrator\Documents\GitHub\linerunner-backend\apps\chanDao\admin.py changed, reloading.
2023-11-02 15:38:55 base.py[line:181] INFO Scheduler started
2023-11-02 15:38:56 base.py[line:181] INFO Scheduler started
2023-11-02 15:39:03 autoreload.py[line:251] INFO C:\Users\Administrator\Documents\GitHub\linerunner-backend\apps\chanDao\models.py changed, reloading.
2023-11-02 15:39:03 autoreload.py[line:251] INFO C:\Users\Administrator\Documents\GitHub\linerunner-backend\apps\chanDao\models.py changed, reloading.
2023-11-02 15:39:04 base.py[line:181] INFO Scheduler started
2023-11-02 15:39:05 base.py[line:181] INFO Scheduler started
2023-11-02 15:39:24 autoreload.py[line:251] INFO C:\Users\Administrator\Documents\GitHub\linerunner-backend\apps\chanDao\serializers.py changed, reloading.
2023-11-02 15:39:25 autoreload.py[line:251] INFO C:\Users\Administrator\Documents\GitHub\linerunner-backend\apps\chanDao\models.py changed, reloading.
2023-11-02 15:39:25 base.py[line:181] INFO Scheduler started
2023-11-02 15:39:26 base.py[line:181] INFO Scheduler started
2023-11-02 15:54:25 autoreload.py[line:251] INFO C:\Users\Administrator\Documents\GitHub\linerunner-backend\apps\report\views.py changed, reloading.
2023-11-02 15:54:25 autoreload.py[line:251] INFO C:\Users\Administrator\Documents\GitHub\linerunner-backend\apps\report\views.py changed, reloading.
2023-11-02 15:54:26 base.py[line:181] INFO Scheduler started
2023-11-02 15:54:27 base.py[line:181] INFO Scheduler started
2023-11-02 15:59:26 autoreload.py[line:251] INFO C:\Users\Administrator\Documents\GitHub\linerunner-backend\apps\report\urls.py changed, reloading.
2023-11-02 15:59:26 autoreload.py[line:251] INFO C:\Users\Administrator\Documents\GitHub\linerunner-backend\apps\report\urls.py changed, reloading.
2023-11-02 15:59:28 base.py[line:181] INFO Scheduler started
2023-11-02 15:59:28 base.py[line:181] INFO Scheduler started
